language: python
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - sudo add-apt-repository ppa:nathan-renniewaldock/ppa
  - sudo apt-get update
  - sudo apt-get -y purge mysql-server-5.1
  - sudo apt-get -y install mysql-server-5.5
  - python setup.py dev
  - pip install psycopg oursql
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script: py.test --tb=native --cov=kotti --cov-report=term-missing
notifications:
  irc: "irc.freenode.org#kotti"
